#!/usr/bin/env bash
# Extended baseline migration — auto-generated by agent
set -euo pipefail
REPO="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO"
LOG="${REPO}/migration-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$LOG") 2>&1

echo "=== STEP 1: fetch upstreams ==="
git fetch upstream master
git fetch metacubex master
git fetch subconverter-extended master
git branch -f upstream-subconverter upstream/master
git branch -f upstream-subconverter-MetaCubeX metacubex/master
git branch -f upstream-SubConverter-Extended subconverter-extended/master

echo "=== STEP 2: backup hjsmaster ==="
git branch -f hjsmaster-blk hjsmaster

echo "=== STEP 3: integration branch from Extended ==="
git checkout -B integrate/extended-hjs upstream-SubConverter-Extended

echo "=== STEP 4: port hjs customizations ==="
git checkout hjsmaster-blk -- deploy/ \
  "docs/技术方案-分支与上游同步.md" \
  "docs/技术迭代-NAS部署与NPM暴露.md" \
  .gitignore

echo "=== STEP 5: maxAllowedRulesets 256 ==="
sed -i '' 's/maxAllowedRulesets = 64/maxAllowedRulesets = 256/' src/handler/settings.h

echo "=== STEP 6: upstream diff补缺 ==="
# Hysteria2 sing-box server_ports helper from hjsmaster-blk if missing
if ! grep -q 'buildSingBoxHysteria2ServerPorts' src/generator/config/subexport.cpp 2>/dev/null; then
  echo "Applying subexport.cpp Hysteria2 server_ports from hjsmaster-blk..."
  git show hjsmaster-blk:src/generator/config/subexport.cpp > /tmp/subexport-hjs.cpp
  git show HEAD:src/generator/config/subexport.cpp > /tmp/subexport-ext.cpp
  # Restore only if hjs has the helper and ext uses naive split
  if grep -q 'buildSingBoxHysteria2ServerPorts' /tmp/subexport-hjs.cpp; then
    python3 <<'PY'
import re, pathlib
hjs = pathlib.Path('/tmp/subexport-hjs.cpp').read_text()
ext = pathlib.Path('/tmp/subexport-ext.cpp').read_text()
m = re.search(r'(static rapidjson::Value buildSingBoxHysteria2ServerPorts[\s\S]*?\n\}\n)', hjs)
if not m:
    raise SystemExit('helper not found in hjs')
helper = m.group(1)
if 'buildSingBoxHysteria2ServerPorts' not in ext:
    # insert before proxyToSingBox
    ext = ext.replace('void proxyToSingBox', helper + '\nvoid proxyToSingBox', 1)
    ext = re.sub(
        r'proxy\.AddMember\("server_ports", stringArrayToJsonArray\(x\.Ports, ",", allocator\), allocator\);',
        'proxy.AddMember("server_ports", buildSingBoxHysteria2ServerPorts(x.Ports, allocator), allocator);',
        ext,
        count=1,
    )
    if '#include <cctype>' not in ext:
        ext = ext.replace('#include <climits>', '#include <climits>\n#include <cctype>', 1)
    pathlib.Path('src/generator/config/subexport.cpp').write_text(ext)
    print('Patched subexport.cpp')
else:
    print('Extended already has buildSingBoxHysteria2ServerPorts')
PY
  fi
fi

# load-balance strategy + ua param from MetaCubeX if missing in binding/interfaces
for f in src/config/binding.h src/handler/interfaces.cpp; do
  if git diff --quiet HEAD hjsmaster-blk -- "$f" 2>/dev/null; then
    echo "$f: no diff vs hjsmaster-blk"
  else
    # Only apply if Extended lacks features hjs has
    if [ "$f" = "src/config/binding.h" ] && ! grep -q 'consistent-hashing' "$f" 2>/dev/null; then
      git checkout hjsmaster-blk -- "$f" || true
      echo "Restored $f from hjsmaster-blk"
    fi
    if [ "$f" = "src/handler/interfaces.cpp" ] && ! grep -q 'argUserAgent' "$f" 2>/dev/null; then
      git checkout hjsmaster-blk -- "$f" || true
      echo "Restored $f from hjsmaster-blk"
    fi
  fi
done

echo "=== STEP 7: commit ==="
git add -A
git commit -m "$(cat <<'EOF'
migrate: rebase hjsmaster onto SubConverter-Extended baseline

Port deploy/, NAS docs, maxAllowedRulesets=256, and upstream feature gaps
(Hysteria2 sing-box server_ports, load-balance/ua where applicable).
EOF
)"

echo "=== STEP 8: rename branches ==="
git branch -D hjsmaster 2>/dev/null || true
git branch -m integrate/extended-hjs hjsmaster

echo "=== STEP 9: docker build ==="
docker buildx build -f deploy/nas/Dockerfile -t subconverter:nas-amd64 --load . || {
  echo "Docker build failed — attempting fix..."
  exit 1
}

echo "=== STEP 10: push ==="
git push origin hjsmaster-blk
git push origin hjsmaster -f
git push origin upstream-subconverter upstream-subconverter-MetaCubeX upstream-SubConverter-Extended

echo "=== STEP 11: NAS deploy ==="
bash deploy/nas/deploy-to-qnap.sh

echo "=== DONE ==="
git log -1 --oneline hjsmaster
git log -1 --oneline hjsmaster-blk
echo "Log: $LOG"
